-- -- Your SQL goes here
-- CREATE TABLE mtg_cards (
--     id varchar(255) NOT NULL PRIMARY KEY,
-- --     oracle_id varchar(255) NOT NULL DEFAULT '',
-- --     multiverse_ids varchar(255) NOT NULL DEFAULT '',
-- --     tcgplayer_id varchar(255) NOT NULL DEFAULT '',
--     name varchar(255) NOT NULL,
-- --     lang varchar(255) NOT NULL,
--     released_at varchar(255) NOT NULL,
--     uri varchar(255) NOT NULL,
-- --     scryfall_uri varchar(255) NOT NULL,
-- --     layout varchar(255) NOT NULL,
-- --     highres_image boolean NOT NULL,
--     image_uris jsonb NOT NULL,
--     mana_cost varchar(255) NOT NULL DEFAULT '',
--     cmc real NOT NULL DEFAULT 0,
--     type_line varchar(255) NOT NULL DEFAULT '',
--     oracle_text varchar(255) NOT NULL DEFAULT '',
--     loyalty varchar(255) NOT NULL DEFAULT '',
--     colors varchar(255) NOT NULL DEFAULT '',
--     color_identity varchar(255) NOT NULL DEFAULT '',
-- --     legalities varchar(255) NOT NULL DEFAULT '',
-- --     games varchar(255) NOT NULL DEFAULT '',
--     reserved boolean NOT NULL,
-- --     foil boolean NOT NULL,
-- --     nonfoil boolean NOT NULL,
-- --     finishes varchar(255) NOT NULL DEFAULT '',
-- --     oversized boolean NOT NULL,
--     promo boolean NOT NULL,
--     reprint boolean NOT NULL,
-- --     variation boolean NOT NULL,
--     set_id varchar(255) NOT NULL DEFAULT '',
--     set_name varchar(255) NOT NULL DEFAULT '',
-- --     set_type varchar(255) NOT NULL DEFAULT '',
--     set_uri varchar(255) NOT NULL DEFAULT '',
--     set_search_uri varchar(255) NOT NULL DEFAULT '',
--     rulings_uri varchar(255) NOT NULL DEFAULT '',
-- --     prints_search_uri varchar(255) NOT NULL DEFAULT '',
--     collector_number varchar(255) NOT NULL DEFAULT '',
--     digital boolean NOT NULL,
--     rarity varchar(255) NOT NULL DEFAULT '',
-- --     card_back_id varchar(255) NOT NULL DEFAULT '',
--     artist varchar(255) NOT NULL DEFAULT '',
-- --     artist_ids varchar(255) NOT NULL DEFAULT '',
-- --     illustration_id varchar(255) NOT NULL DEFAULT '',
-- --     border_color varchar(255) NOT NULL DEFAULT '',
--     frame varchar(255) NOT NULL DEFAULT '',
-- --     frame_effects varchar(255) NOT NULL DEFAULT '',
--     security_stamp varchar(255) NOT NULL DEFAULT '',
--     full_art boolean NOT NULL,
--     textless boolean NOT NULL,
-- --     booster boolean NOT NULL,
-- --     story_spotlight boolean NOT NULL,
--     edhrec_rank integer NOT NULL DEFAULT 0,
-- --     penny_rank integer NOT NULL DEFAULT 0,
--     prices jsonb NOT NULL,
-- --     related_uris varchar(255) NOT NULL DEFAULT '',
--     purchase_uris jsonb NOT NULL
-- )

-- CREATE TABLE mtg_cards (
--     id varchar(255) NOT NULL PRIMARY KEY,
--     name varchar(255) not null,
--     prices jsonb not null
-- )

CREATE TABLE mtg_cards (
    id varchar(255) NOT NULL PRIMARY KEY,
    name varchar(255) not null,
    released_at varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    mana_cost varchar(255) NOT NULL DEFAULT '',
    cmc real NOT NULL DEFAULT 0,
    type_line varchar(255) NOT NULL DEFAULT '',
    oracle_text TEXT NOT NULL DEFAULT '',
    loyalty varchar(255) NOT NULL DEFAULT '',
    reserved boolean NOT NULL,
    promo boolean NOT NULL,
    reprint boolean NOT NULL,
    set_id varchar(255) NOT NULL DEFAULT '',
    set_name varchar(255) NOT NULL DEFAULT '',
    set_search_uri TEXT NOT NULL DEFAULT '',
    rulings_uri TEXT NOT NULL DEFAULT '',
    collector_number varchar(255) NOT NULL DEFAULT '',
    digital boolean NOT NULL,
    rarity varchar(255) NOT NULL DEFAULT '',
    artist varchar(255) NOT NULL DEFAULT '',
    frame varchar(255) NOT NULL DEFAULT '',
    security_stamp varchar(255) NOT NULL DEFAULT '',
    full_art boolean NOT NULL,
    textless boolean NOT NULL,
    edhrec_rank integer NOT NULL DEFAULT 0,
    prices jsonb NOT NULL,
    purchase_uris jsonb NOT NULL
)